=== rasa/scoops/schema.json
{
    "$id": "http://scoop.sh/draft/schema#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "definitions": {
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "bin": {
                    "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
                },
                "checkver": {
                    "$ref": "#/definitions/checkver"
                },
                "extract_dir": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "hash": {
                    "$ref": "#/definitions/hash"
                },
                "installer": {
                    "$ref": "#/definitions/installer"
                },
                "msi": {
                    "$ref": "#/definitions/stringOrArrayOfStrings",
                    "description": "Deprecated"
                },
                "post_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "pre_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "shortcuts": {
                    "$ref": "#/definitions/shortcutsArray"
                },
                "uninstaller": {
                    "$ref": "#/definitions/uninstaller"
                },
                "url": {
                    "$ref": "#/definitions/uriOrArrayOfUris"
                }
            },
            "type": "object"
        },
        "arrayOfArrayOfStrings": {
            "items": {
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "autoupdate": {
            "additionalProperties": false,
            "properties": {
                "architecture": {
                    "additionalProperties": false,
                    "properties": {
                        "32bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "64bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        }
                    },
                    "type": "object"
                },
                "extract_dir": {
                    "type": "string"
                },
                "hash": {
                    "$ref": "#/definitions/hashExtraction"
                },
                "note": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "url": {
                    "format": "uri",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "checkver": {
            "anyOf": [
                {
                    "format": "regex",
                    "type": "string"
                },
                {
                    "additionalProperties": false,
                    "properties": {
                        "github": {
                            "format": "uri",
                            "type": "string"
                        },
                        "jp": {
                            "pattern": "^\\$\\..*$",
                            "type": "string"
                        },
                        "re": {
                            "format": "regex",
                            "type": "string"
                        },
                        "replace": {
                            "description": "Allows rearrange the regexp matches",
                            "type": "string"
                        },
                        "reverse": {
                            "description": "Reverse the order of regex matches",
                            "type": "boolean"
                        },
                        "url": {
                            "format": "uri",
                            "type": "string"
                        }
                    },
                    "type": "object"
                }
            ]
        },
        "hash": {
            "anyOf": [
                {
                    "$ref": "#/definitions/hashPattern"
                },
                {
                    "items": {
                        "$ref": "#/definitions/hashPattern"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        },
        "hashExtraction": {
            "additionalProperties": false,
            "properties": {
                "find": {
                    "format": "regex",
                    "type": "string"
                },
                "jp": {
                    "pattern": "^\\$\\..*$",
                    "type": "string"
                },
                "mode": {
                    "enum": [
                        "download",
                        "extract",
                        "json",
                        "rdf"
                    ]
                },
                "type": {
                    "description": "Deprecated, hash type is determined automatically",
                    "enum": [
                        "md5",
                        "sha1",
                        "sha256",
                        "sha512"
                    ]
                },
                "url": {
                    "anyOf": [
                        {
                            "format": "uri",
                            "type": "string"
                        },
                        {
                            "pattern": "^(\\$url|\\$baseurl).[\\w\\d]+$",
                            "type": "string"
                        },
                        {
                            "pattern": "^.*(\\$url|\\$baseurl).*$",
                            "type": "string"
                        }
                    ]
                }
            },
            "type": "object"
        },
        "hashPattern": {
            "pattern": "^([a-fA-F0-9]{64}|(sha1|sha256|sha512|md5):([a-fA-F0-9]{32}|[a-fA-F0-9]{40}|[a-fA-F0-9]{64}|[a-fA-F0-9]{128}))$",
            "type": "string"
        },
        "installer": {
            "additionalProperties": false,
            "properties": {
                "_comment": {
                    "description": "Undocumented: only used in scoop-extras/oraclejdk* and scoop-extras/appengine-go",
                    "type": "string"
                },
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "keep": {
                    "type": "boolean"
                },
                "script": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "shortcutsArray": {
            "items": {
                "items": {
                    "type": "string"
                },
                "maxItems": 4,
                "minItems": 2,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "stringOrArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "stringOrArrayOfStringsOrAnArrayOfArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "$ref": "#/definitions/stringOrArrayOfStrings"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "uninstaller": {
            "oneOf": [
                {
                    "required": [
                        "file"
                    ]
                },
                {
                    "required": [
                        "script"
                    ]
                }
            ],
            "properties": {
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "script": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "uriOrArrayOfUris": {
            "anyOf": [
                {
                    "format": "uri",
                    "not": {
                        "pattern": "(\\$)"
                    },
                    "type": "string"
                },
                {
                    "items": {
                        "format": "uri",
                        "not": {
                            "pattern": "(\\$)"
                        },
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        }
    },
    "properties": {
        "##": {
            "description": "A comment.",
            "type": "string"
        },
        "_comment": {
            "description": "Undocumented: only found in scoop/git* and 6 manifests in scoop-extras",
            "type": "string"
        },
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "32bit": {
                    "$ref": "#/definitions/architecture"
                },
                "64bit": {
                    "$ref": "#/definitions/architecture"
                }
            },
            "type": "object"
        },
        "autoupdate": {
            "$ref": "#/definitions/autoupdate"
        },
        "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "checkver": {
            "$ref": "#/definitions/checkver"
        },
        "cookie": {
            "description": "Undocumented: only found in scoop-extras/oraclejdk*",
            "type": "object"
        },
        "depends": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "description": {
            "description": "Undocumented: only found in scoop/gibo",
            "type": "string"
        },
        "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "env_set": {
            "type": "object"
        },
        "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "extract_to": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Undocumented: only found in scoop/ruby*"
        },
        "hash": {
            "$ref": "#/definitions/hash"
        },
        "homepage": {
            "format": "uri",
            "type": "string"
        },
        "innosetup": {
            "description": "Undocumented: only found in 6 manifests in scoop",
            "type": "boolean"
        },
        "installer": {
            "$ref": "#/definitions/installer"
        },
        "license": {
            "type": "string"
        },
        "msi": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Deprecated"
        },
        "notes": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "persist": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "post_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "pre_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "psmodule": {
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
        },
        "suggest": {
            "additionalProperties": false,
            "patternProperties": {
                "^(.*)$": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "type": "object"
        },
        "uninstaller": {
            "$ref": "#/definitions/uninstaller"
        },
        "url": {
            "$ref": "#/definitions/uriOrArrayOfUris"
        },
        "version": {
            "pattern": "^[\\w\\.\\-_]+$",
            "type": "string"
        }
    },
    "required": [
        "version"
    ],
    "title": "scoop app manifest schema",
    "type": "object"
}

=== rasa/scoops/bucket/restartsrdev.json
{
    "version": "3.0",
    "description": "Restart safely removed media",
    "homepage": "http://www.uwe-sieber.de/drivetools_e.html",
    "license": "Freeware",
    "notes": "RestartSrDev.exe reports it's actually version 2.0.1",
    "architecture": {
        "32bit": {
            "bin": "Win32/RestartSrDev.exe"
        },
        "64bit": {
            "bin": "x64/RestartSrDev.exe"
        }
    },
    "url": "http://www.uwe-sieber.de/files/restartsrdev.zip",
    "hash": "55a28b8f7d974300b763e7a7ec675e2288600e9f095d5846a4ec56063c7b67b6",
    "checkver": "RestartSrDev\\s+V([\\d.]+)\\s+-\\s+restarts",
    "autoupdate": {
        "url": "http://www.uwe-sieber.de/files/restartsrdev.zip"
    }
}

=== rasa/scoops/ztree-beta.json
{
    "hash": "eb8c4c5b80ddc4c31227249b7d1af2dfe85d86bbe73e6bd44f254948f141f75f",
    "description": "Text-mode file/directory manager (beta version)",
    "license": "Shareware",
    "checkver": {
        "re": ";\">v([\\d.]+)<"
    },
    "url": "http://www.zedtek.com/download/ztw24181.zip",
    "notes": [
        "There is no way to uninstall just the beta version"
    ],
    "depends": [
        "ztree"
    ],
    "version": "2.4.181",
    "autoupdate": {
        "url": "http://www.zedtek.com/download/ztw$cleanVersion.zip"
    },
    "homepage": "http://www.ztree.com/html/beta.htm",
    "post_install": [
        "cp \"$dir/*.*\" \"$(appdir ztree $global)/current\""
    ]
}

=== rasa/scoops/vlc-installer.json
{
    "architecture": {
        "32bit": {
            "hash": "67b8ea781fda9f8c13f672443dab0a437c4365fb757e121234f3ad0f2dc654a7",
            "url": "https://github.com/rasa/vlc_installer/releases/download/v2.2.4/vlc_installer-2.2.4-win32.zip"
        },
        "64bit": {
            "hash": "12910e0b8785d778247e431e2f05f7cb14869265569ef075539fd0e6a35a48b4",
            "url": "https://github.com/rasa/vlc_installer/releases/download/v2.2.4/vlc_installer-2.2.4-win64.zip"
        }
    },
    "autoupdate": {
        "architecture": {
            "32bit": {
                "url": "https://github.com/rasa/vlc_installer/releases/download/v$version/vlc_installer-$version-win32.zip"
            },
            "64bit": {
                "url": "https://github.com/rasa/vlc_installer/releases/download/v$version/vlc_installer-$version-win64.zip"
            }
        }
    },
    "checkver": "github",
    "description": "Download and install the VLC media player and related plugins (deprecated)",
    "homepage": "https://github.com/rasa/vlc_installer",
    "installer": {
        "args": [
            "/S",
            "/D=\"$dir\""
        ],
        "file": "vlc_installer.exe"
    },
    "license": "MIT",
    "notes": "WARNING: The uninstaller will display a popup window",
    "uninstaller": {
        "args": "/S",
        "file": "Uninstall-vlc_installer.exe"
    },
    "version": "2.2.4"
}

=== rasa/scoops/bucket/ffb.json
{
    "_comment": "checkver to be: FFB\\s+V([\\d.]+)\\s+-\\s+Flush",
    "version": "1.0",
    "description": "Flush file buffers",
    "homepage": "http://www.uwe-sieber.de/drivetools_e.html",
    "license": "Freeware",
    "architecture": {
        "32bit": {
            "bin": "Win32/FFB.exe"
        },
        "64bit": {
            "bin": "x64/FFB.exe"
        }
    },
    "url": "http://www.uwe-sieber.de/files/FFB.zip",
    "hash": "39cc8733c26a28b1acd5a9c7f12b9ea5f248ded4235f8912c4b7385e9a2b9060",
    "autoupdate": {
        "url": "http://www.uwe-sieber.de/files/FFB.zip"
    }
}

=== rasa/scoops/removedrive.json
{
    "architecture": {
        "32bit": {
            "bin": "Win32/RemoveDrive.exe"
        },
        "64bit": {
            "bin": "x64/RemoveDrive.exe"
        }
    },
    "checkver": "RemoveDrive\\s+V([\\d.]+)\\s+-\\s+Safe",
    "description": "Safely removes drives",
    "hash": "83fb65e81f645d46d302b1a0a0bcfae189548a609bbd5aeaa7b9297c75f3abf1",
    "homepage": "http://www.uwe-sieber.de/drivetools_e.html",
    "license": "Freeware",
    "url": "http://www.uwe-sieber.de/files/removedrive.zip",
    "version": "2.8.6"
}

=== rasa/scoops/rescandevices.json
{
    "version": "0.1",
    "description": "Rescan devices",
    "homepage": "http://www.uwe-sieber.de/drivetools_e.html",
    "license": "Freeware",
    "hash": "68c28b4e8e84cbad0b8ac9c0963efd51ed95da36838af6927b732af68b5c4adc",
    "url": "http://www.uwe-sieber.de/files/rescandevices.zip",
    "bin": "RescanDevices.exe",
    "autoupdate": {
        "url": "http://www.uwe-sieber.de/files/rescandevices.zip"
    }
}

=== rasa/scoops/wip/ztree-beta.json
{
    "architecture": {
        "32bit": {
            "bin": [
                "ztw.exe"
            ],
            "installer": {
                "args": [
                    "/S",
                    "/D=$dir"
                ],
                "file": "ztw22x86.exe"
            },
            "url": [
                "http://www.zedtek.com/download/ztw22x86.exe",
                "http://www.zedtek.com/download/ztw24181.zip"
            ]
        },
        "64bit": {
            "bin": [
                [
                    "ztw64.exe",
                    "ztw"
                ]
            ],
            "installer": {
                "args": [
                    "/S",
                    "/D=$dir"
                ],
                "file": "ztw22x64.exe"
            },
            "url": [
                "http://www.zedtek.com/download/ztw22x64.exe",
                "http://www.zedtek.com/download/ztw24181.zip"
            ]
        }
    },
    "homepage": "http://www.ztree.com/",
    "license": "Proprietary",
    "uninstaller": {
        "args": [
            "/S"
        ],
        "file": "Uninstall.exe"
    },
    "version": "2.4.181"
}

=== rasa/scoops/cherrytree.json
{
    "autoupdate": {
        "url": "http://www.giuspen.com/software/cherrytree_$version_win32_portable.7z"
    },
    "bin": "bin/cherrytree.exe",
    "checkver": {
        "re": "http://www.giuspen.com/software/cherrytree_([\\d.]+)_win32_portable.7z"
    },
    "description": "Hierarchical note taking application",
    "extract_dir": "cherrytree_0.38.4_win32_portable",
    "hash": "44fc5c5152fbb9398da6c96f47fbf543bd4792d6fa8cf6b63bd5fc67a9499fd4",
    "homepage": "https://www.giuspen.com/cherrytree",
    "license": "GPL-3.0",
    "shortcuts": [
        [
            "bin/cherrytree.exe",
            "Cherrytree - A hierarchical note taking application"
        ]
    ],
    "url": "http://www.giuspen.com/software/cherrytree_0.38.6_win32_portable.7z",
    "version": "0.38.6"
}
