=== rasa/scoops/schema.json
{
    "$id": "http://scoop.sh/draft/schema#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "definitions": {
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "bin": {
                    "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
                },
                "checkver": {
                    "$ref": "#/definitions/checkver"
                },
                "extract_dir": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "hash": {
                    "$ref": "#/definitions/hash"
                },
                "installer": {
                    "$ref": "#/definitions/installer"
                },
                "msi": {
                    "$ref": "#/definitions/stringOrArrayOfStrings",
                    "description": "Deprecated"
                },
                "post_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "pre_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "shortcuts": {
                    "$ref": "#/definitions/shortcutsArray"
                },
                "uninstaller": {
                    "$ref": "#/definitions/uninstaller"
                },
                "url": {
                    "$ref": "#/definitions/uriOrArrayOfUris"
                }
            },
            "type": "object"
        },
        "arrayOfArrayOfStrings": {
            "items": {
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "autoupdate": {
            "additionalProperties": false,
            "properties": {
                "architecture": {
                    "additionalProperties": false,
                    "properties": {
                        "32bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "64bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        }
                    },
                    "type": "object"
                },
                "extract_dir": {
                    "type": "string"
                },
                "hash": {
                    "$ref": "#/definitions/hashExtraction"
                },
                "note": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "url": {
                    "format": "uri",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "checkver": {
            "anyOf": [
                {
                    "format": "regex",
                    "type": "string"
                },
                {
                    "additionalProperties": false,
                    "properties": {
                        "github": {
                            "format": "uri",
                            "type": "string"
                        },
                        "jp": {
                            "pattern": "^\\$\\..*$",
                            "type": "string"
                        },
                        "re": {
                            "format": "regex",
                            "type": "string"
                        },
                        "replace": {
                            "description": "Allows rearrange the regexp matches",
                            "type": "string"
                        },
                        "reverse": {
                            "description": "Reverse the order of regex matches",
                            "type": "boolean"
                        },
                        "url": {
                            "format": "uri",
                            "type": "string"
                        }
                    },
                    "type": "object"
                }
            ]
        },
        "hash": {
            "anyOf": [
                {
                    "$ref": "#/definitions/hashPattern"
                },
                {
                    "items": {
                        "$ref": "#/definitions/hashPattern"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        },
        "hashExtraction": {
            "additionalProperties": false,
            "properties": {
                "find": {
                    "format": "regex",
                    "type": "string"
                },
                "jp": {
                    "pattern": "^\\$\\..*$",
                    "type": "string"
                },
                "mode": {
                    "enum": [
                        "download",
                        "extract",
                        "json",
                        "rdf"
                    ]
                },
                "type": {
                    "description": "Deprecated, hash type is determined automatically",
                    "enum": [
                        "md5",
                        "sha1",
                        "sha256",
                        "sha512"
                    ]
                },
                "url": {
                    "anyOf": [
                        {
                            "format": "uri",
                            "type": "string"
                        },
                        {
                            "pattern": "^(\\$url|\\$baseurl).[\\w\\d]+$",
                            "type": "string"
                        },
                        {
                            "pattern": "^.*(\\$url|\\$baseurl).*$",
                            "type": "string"
                        }
                    ]
                }
            },
            "type": "object"
        },
        "hashPattern": {
            "pattern": "^([a-fA-F0-9]{64}|(sha1|sha256|sha512|md5):([a-fA-F0-9]{32}|[a-fA-F0-9]{40}|[a-fA-F0-9]{64}|[a-fA-F0-9]{128}))$",
            "type": "string"
        },
        "installer": {
            "additionalProperties": false,
            "properties": {
                "_comment": {
                    "description": "Undocumented: only used in scoop-extras/oraclejdk* and scoop-extras/appengine-go",
                    "type": "string"
                },
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "keep": {
                    "type": "boolean"
                },
                "script": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "shortcutsArray": {
            "items": {
                "items": {
                    "type": "string"
                },
                "maxItems": 4,
                "minItems": 2,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "stringOrArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "stringOrArrayOfStringsOrAnArrayOfArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "$ref": "#/definitions/stringOrArrayOfStrings"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "uninstaller": {
            "oneOf": [
                {
                    "required": [
                        "file"
                    ]
                },
                {
                    "required": [
                        "script"
                    ]
                }
            ],
            "properties": {
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "script": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "uriOrArrayOfUris": {
            "anyOf": [
                {
                    "format": "uri",
                    "not": {
                        "pattern": "(\\$)"
                    },
                    "type": "string"
                },
                {
                    "items": {
                        "format": "uri",
                        "not": {
                            "pattern": "(\\$)"
                        },
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        }
    },
    "properties": {
        "##": {
            "description": "A comment.",
            "type": "string"
        },
        "_comment": {
            "description": "Undocumented: only found in scoop/git* and 6 manifests in scoop-extras",
            "type": "string"
        },
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "32bit": {
                    "$ref": "#/definitions/architecture"
                },
                "64bit": {
                    "$ref": "#/definitions/architecture"
                }
            },
            "type": "object"
        },
        "autoupdate": {
            "$ref": "#/definitions/autoupdate"
        },
        "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "checkver": {
            "$ref": "#/definitions/checkver"
        },
        "cookie": {
            "description": "Undocumented: only found in scoop-extras/oraclejdk*",
            "type": "object"
        },
        "depends": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "description": {
            "description": "Undocumented: only found in scoop/gibo",
            "type": "string"
        },
        "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "env_set": {
            "type": "object"
        },
        "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "extract_to": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Undocumented: only found in scoop/ruby*"
        },
        "hash": {
            "$ref": "#/definitions/hash"
        },
        "homepage": {
            "format": "uri",
            "type": "string"
        },
        "innosetup": {
            "description": "Undocumented: only found in 6 manifests in scoop",
            "type": "boolean"
        },
        "installer": {
            "$ref": "#/definitions/installer"
        },
        "license": {
            "type": "string"
        },
        "msi": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Deprecated"
        },
        "notes": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "persist": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "post_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "pre_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "psmodule": {
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
        },
        "suggest": {
            "additionalProperties": false,
            "patternProperties": {
                "^(.*)$": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "type": "object"
        },
        "uninstaller": {
            "$ref": "#/definitions/uninstaller"
        },
        "url": {
            "$ref": "#/definitions/uriOrArrayOfUris"
        },
        "version": {
            "pattern": "^[\\w\\.\\-_]+$",
            "type": "string"
        }
    },
    "required": [
        "version"
    ],
    "title": "scoop app manifest schema",
    "type": "object"
}

=== rasa/scoops/time-it.json
{
    "bin": "time_it.exe",
    "hash": "8acdd6249cc168256a75900f51447d5b65105219eb61288b55c949e683bd7725",
    "description": "Time disk I/O",
    "license": "MIT",
    "checkver": "github",
    "url": "https://github.com/rasa/time_it/releases/download/v1.2/time_it-1.2-win32.zip",
    "version": "1.2",
    "autoupdate": {
        "url": "https://github.com/rasa/time_it/releases/download/v$version/time_it-$version-win32.zip"
    },
    "homepage": "https://github.com/rasa/time_it"
}

=== rasa/scoops/inadyn-mt.json
{
    "autoupdate": {
        "extract_dir": "inadyn-mt.v.$version",
        "url": "https://sourceforge.net/projects/inadyn-mt/files/inadyn-mt/inadyn-mt.v.$version/inadyn-mt.v.$version.tar.gz"
    },
    "bin": [
        "bin/win32/inadyn-mt.exe"
    ],
    "checkver": "title=\"/inadyn-mt/inadyn-mt\\.v\\.([\\d.]+)",
    "description": "Dynamic DNS client",
    "extract_dir": "inadyn-mt.v.02.28.10",
    "hash": "f69bea12d96b66f9f662a8df0730c60457b24f5fb5308b109936880ebf7be5ca",
    "homepage": "https://sourceforge.net/projects/inadyn-mt/files/inadyn-mt/",
    "license": "GPL-3.0",
    "url": "https://sourceforge.net/projects/inadyn-mt/files/inadyn-mt/inadyn-mt.v.02.28.10/inadyn-mt.v.02.28.10.tar.gz",
    "version": "02.28.10"
}

=== rasa/scoops/restartsrdev.json
{
    "hash": "f401521063b6c0ce30c8d659e7e5f7629abc07bdb6814adc2bda8b5a34cf7c92",
    "description": "Restart safely removed media",
    "license": "Freeware",
    "checkver": "RestartSrDev\\s+V([\\d.]+)\\s+-\\s+restarts",
    "url": "http://www.uwe-sieber.de/files/restartsrdev.zip",
    "notes": "RestartSrDev.exe reports it's actually version 2.0.1",
    "version": "2.2",
    "architecture": {
        "32bit": {
            "bin": "Win32/RestartSrDev.exe"
        },
        "64bit": {
            "bin": "x64/RestartSrDev.exe"
        }
    },
    "autoupdate": {
        "url": "http://www.uwe-sieber.de/files/restartsrdev.zip"
    },
    "homepage": "http://www.uwe-sieber.de/drivetools_e.html"
}

=== rasa/scoops/hash-explorer.json
{
    "pre_install": "& \"$dir/setup.exe\" /SP- /SILENT /NOCANCEL /NOCLOSEAPPLICATIONS /NORESTART /DIR=\"$dir\"",
    "bin": "Toms Hash Explorer.exe",
    "hash": "f9b205b73e3891dfd6d3aa455f2c922da0803af2f84fd73ea9bcef520d48d006",
    "description": "Calculate cryptographic hash values (GUI)",
    "license": "Freeware",
    "url": "http://www.mannerud.org/tom-andreas/downloads/Toms_Hash_Explorer_v1.2.zip",
    "uninstaller": {
        "file": "unins000.exe"
    },
    "shortcuts": [
        [
            "Toms Hash Explorer.exe",
            "Tom's Hash Explorer"
        ]
    ],
    "version": "1.2",
    "homepage": "https://www.mannerud.org/tom-andreas/software/toms-hash-explorer/"
}

=== rasa/scoops/bucket/gifsicle.json
{
    "version": "1.95",
    "description": "Manipulate GIF images",
    "homepage": "https://eternallybored.org/misc/gifsicle/",
    "license": "GPL-2.0-only",
    "architecture": {
        "32bit": {
            "extract_dir": "gifsicle-1.95",
            "url": "https://eternallybored.org/misc/gifsicle/releases/gifsicle-1.95-win32.zip",
            "hash": "f31464e334b9fb83d4dc60a25bde7cfa35829564bc378c40f0d3c6350910256c"
        },
        "64bit": {
            "extract_dir": "gifsicle-1.95",
            "url": "https://eternallybored.org/misc/gifsicle/releases/gifsicle-1.95-win64.zip",
            "hash": "7e47dd0bfd5ee47f911464c57faeed89a8709a7625dd1c449b16579889539ee8"
        }
    },
    "bin": [
        "gifdiff.exe",
        "gifsicle.exe"
    ],
    "checkver": "href=\"releases/gifsicle-([\\d.]+)",
    "autoupdate": {
        "architecture": {
            "32bit": {
                "extract_dir": "gifsicle-$version",
                "url": "https://eternallybored.org/misc/gifsicle/releases/gifsicle-$version-win32.zip"
            },
            "64bit": {
                "extract_dir": "gifsicle-$version",
                "url": "https://eternallybored.org/misc/gifsicle/releases/gifsicle-$version-win64.zip"
            }
        }
    }
}

=== rasa/scoops/remount.json
{
    "architecture": {
        "32bit": {
            "bin": "Win32/remount.exe"
        },
        "64bit": {
            "bin": "x64/remount.exe"
        }
    },
    "autoupdate": {
        "url": "http://www.uwe-sieber.de/files/remount.zip"
    },
    "checkver": "ReMount\\s+V([\\d.]+)\\s+-",
    "description": "Remount ejected volumes",
    "hash": "37f9761877cc1b0dc1806045e1d9435f535f226d8b2faefedf615b4de32cd72f",
    "homepage": "http://www.uwe-sieber.de/drivetools_e.html",
    "license": "Freeware",
    "url": "http://www.uwe-sieber.de/files/remount.zip",
    "version": "2.1"
}

=== rasa/scoops/bucket/pfm2afm.json
{
    "version": "1.11",
    "description": "Convert .PFM files to .AFM files",
    "license": "Freeware",
    "url": "https://www.slosipe.org/media/html2pdf/_tcpdf_5.0.002/fonts/utils/pfm2afm.exe",
    "hash": "b6582404f57010e8a000c1fd6b9ec6100016588a15c629ac615834c0125d132e",
    "bin": "pfm2afm.exe"
}

=== rasa/scoops/babelmap.json
{
    "autoupdate": {
        "url": "http://www.babelstone.co.uk/Software/Download/BabelMap.zip"
    },
    "bin": "BabelMap.exe",
    "checkver": ">\\s*Version\\s+([\\d.]+)\\s+\\(",
    "description": "Display Unicode character maps",
    "hash": "65aac63644ca83fcc4beb37b4895bfc852c8cba465e7a60686f40b9c622f5452",
    "homepage": "http://www.babelstone.co.uk/Software/BabelMap.html",
    "license": "Freeware",
    "shortcuts": [
        [
            "BabelMap.exe",
            "BabelMap - Unicode character map viewer"
        ]
    ],
    "url": "http://www.babelstone.co.uk/Software/Download/BabelMap.zip",
    "version": "11.0.0.1"
}
