=== rasa/scoops/schema.json
{
    "$id": "http://scoop.sh/draft/schema#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "definitions": {
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "bin": {
                    "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
                },
                "checkver": {
                    "$ref": "#/definitions/checkver"
                },
                "extract_dir": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "hash": {
                    "$ref": "#/definitions/hash"
                },
                "installer": {
                    "$ref": "#/definitions/installer"
                },
                "msi": {
                    "$ref": "#/definitions/stringOrArrayOfStrings",
                    "description": "Deprecated"
                },
                "post_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "pre_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "shortcuts": {
                    "$ref": "#/definitions/shortcutsArray"
                },
                "uninstaller": {
                    "$ref": "#/definitions/uninstaller"
                },
                "url": {
                    "$ref": "#/definitions/uriOrArrayOfUris"
                }
            },
            "type": "object"
        },
        "arrayOfArrayOfStrings": {
            "items": {
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "autoupdate": {
            "additionalProperties": false,
            "properties": {
                "architecture": {
                    "additionalProperties": false,
                    "properties": {
                        "32bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "64bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        }
                    },
                    "type": "object"
                },
                "extract_dir": {
                    "type": "string"
                },
                "hash": {
                    "$ref": "#/definitions/hashExtraction"
                },
                "note": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "url": {
                    "format": "uri",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "checkver": {
            "anyOf": [
                {
                    "format": "regex",
                    "type": "string"
                },
                {
                    "additionalProperties": false,
                    "properties": {
                        "github": {
                            "format": "uri",
                            "type": "string"
                        },
                        "jp": {
                            "pattern": "^\\$\\..*$",
                            "type": "string"
                        },
                        "re": {
                            "format": "regex",
                            "type": "string"
                        },
                        "replace": {
                            "description": "Allows rearrange the regexp matches",
                            "type": "string"
                        },
                        "reverse": {
                            "description": "Reverse the order of regex matches",
                            "type": "boolean"
                        },
                        "url": {
                            "format": "uri",
                            "type": "string"
                        }
                    },
                    "type": "object"
                }
            ]
        },
        "hash": {
            "anyOf": [
                {
                    "$ref": "#/definitions/hashPattern"
                },
                {
                    "items": {
                        "$ref": "#/definitions/hashPattern"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        },
        "hashExtraction": {
            "additionalProperties": false,
            "properties": {
                "find": {
                    "format": "regex",
                    "type": "string"
                },
                "jp": {
                    "pattern": "^\\$\\..*$",
                    "type": "string"
                },
                "mode": {
                    "enum": [
                        "download",
                        "extract",
                        "json",
                        "rdf"
                    ]
                },
                "type": {
                    "description": "Deprecated, hash type is determined automatically",
                    "enum": [
                        "md5",
                        "sha1",
                        "sha256",
                        "sha512"
                    ]
                },
                "url": {
                    "anyOf": [
                        {
                            "format": "uri",
                            "type": "string"
                        },
                        {
                            "pattern": "^(\\$url|\\$baseurl).[\\w\\d]+$",
                            "type": "string"
                        },
                        {
                            "pattern": "^.*(\\$url|\\$baseurl).*$",
                            "type": "string"
                        }
                    ]
                }
            },
            "type": "object"
        },
        "hashPattern": {
            "pattern": "^([a-fA-F0-9]{64}|(sha1|sha256|sha512|md5):([a-fA-F0-9]{32}|[a-fA-F0-9]{40}|[a-fA-F0-9]{64}|[a-fA-F0-9]{128}))$",
            "type": "string"
        },
        "installer": {
            "additionalProperties": false,
            "properties": {
                "_comment": {
                    "description": "Undocumented: only used in scoop-extras/oraclejdk* and scoop-extras/appengine-go",
                    "type": "string"
                },
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "keep": {
                    "type": "boolean"
                },
                "script": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "shortcutsArray": {
            "items": {
                "items": {
                    "type": "string"
                },
                "maxItems": 4,
                "minItems": 2,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "stringOrArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "stringOrArrayOfStringsOrAnArrayOfArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "$ref": "#/definitions/stringOrArrayOfStrings"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "uninstaller": {
            "oneOf": [
                {
                    "required": [
                        "file"
                    ]
                },
                {
                    "required": [
                        "script"
                    ]
                }
            ],
            "properties": {
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "script": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "uriOrArrayOfUris": {
            "anyOf": [
                {
                    "format": "uri",
                    "not": {
                        "pattern": "(\\$)"
                    },
                    "type": "string"
                },
                {
                    "items": {
                        "format": "uri",
                        "not": {
                            "pattern": "(\\$)"
                        },
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        }
    },
    "properties": {
        "##": {
            "description": "A comment.",
            "type": "string"
        },
        "_comment": {
            "description": "Undocumented: only found in scoop/git* and 6 manifests in scoop-extras",
            "type": "string"
        },
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "32bit": {
                    "$ref": "#/definitions/architecture"
                },
                "64bit": {
                    "$ref": "#/definitions/architecture"
                }
            },
            "type": "object"
        },
        "autoupdate": {
            "$ref": "#/definitions/autoupdate"
        },
        "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "checkver": {
            "$ref": "#/definitions/checkver"
        },
        "cookie": {
            "description": "Undocumented: only found in scoop-extras/oraclejdk*",
            "type": "object"
        },
        "depends": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "description": {
            "description": "Undocumented: only found in scoop/gibo",
            "type": "string"
        },
        "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "env_set": {
            "type": "object"
        },
        "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "extract_to": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Undocumented: only found in scoop/ruby*"
        },
        "hash": {
            "$ref": "#/definitions/hash"
        },
        "homepage": {
            "format": "uri",
            "type": "string"
        },
        "innosetup": {
            "description": "Undocumented: only found in 6 manifests in scoop",
            "type": "boolean"
        },
        "installer": {
            "$ref": "#/definitions/installer"
        },
        "license": {
            "type": "string"
        },
        "msi": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Deprecated"
        },
        "notes": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "persist": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "post_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "pre_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "psmodule": {
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
        },
        "suggest": {
            "additionalProperties": false,
            "patternProperties": {
                "^(.*)$": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "type": "object"
        },
        "uninstaller": {
            "$ref": "#/definitions/uninstaller"
        },
        "url": {
            "$ref": "#/definitions/uriOrArrayOfUris"
        },
        "version": {
            "pattern": "^[\\w\\.\\-_]+$",
            "type": "string"
        }
    },
    "required": [
        "version"
    ],
    "title": "scoop app manifest schema",
    "type": "object"
}

=== rasa/scoops/usbtreeview.json
{
    "architecture": {
        "32bit": {
            "extract_dir": "Win32"
        },
        "64bit": {
            "extract_dir": "x64"
        }
    },
    "autoupdate": {
        "url": "http://www.uwe-sieber.de/files/usbtreeview.zip"
    },
    "bin": "usbtreeview.exe",
    "checkver": "USB Device Tree Viewer V([\\d.]+)",
    "description": "USB device tree viewer",
    "hash": "9b03d8603d0b68a5e333a6b6cfa99d806a3c2da18cc2395322662c51f92cb55c",
    "homepage": "http://www.uwe-sieber.de/usbtreeview_e.html",
    "license": "Freeware",
    "shortcuts": [
        [
            "usbtreeview.exe",
            "UsbTreeView - USB Device Tree Viewer"
        ]
    ],
    "url": "http://www.uwe-sieber.de/files/usbtreeview.zip",
    "version": "3.2.3"
}

=== rasa/scoops/simple-dnscrypt.json
{
    "architecture": {
        "32bit": {
            "hash": "d24a4928f0a5f5ccc4a325d65d1f90e5d4aa2e5b5ff3659777d552b99b77d662",
            "url": "https://github.com/bitbeans/SimpleDnsCrypt/releases/download/0.6.0/SimpleDNSCrypt.msi"
        },
        "64bit": {
            "hash": "99803f50ad4049f08513caa1ee080484aa9dd9257fab1f7f949e2c43cbd6e734",
            "url": "https://github.com/bitbeans/SimpleDnsCrypt/releases/download/0.6.0/SimpleDNSCrypt64.msi"
        }
    },
    "autoupdate": {
        "architecture": {
            "32bit": {
                "url": "https://github.com/bitbeans/SimpleDnsCrypt/releases/download/$version/SimpleDNSCrypt.msi"
            },
            "64bit": {
                "url": "https://github.com/bitbeans/SimpleDnsCrypt/releases/download/$version/SimpleDNSCrypt64.msi"
            }
        }
    },
    "bin": "SimpleDnsCrypt.exe",
    "checkver": {
        "github": "https://github.com/bitbeans/SimpleDnsCrypt"
    },
    "description": "Simple management tool for dnscrypt-proxy",
    "homepage": "https://simplednscrypt.org/",
    "license": "MIT",
    "shortcuts": [
        [
            "SimpleDnsCrypt.exe",
            "Simple DNSCrypt"
        ]
    ],
    "uninstaller": {
        "file": "Uninstall.exe"
    },
    "version": "0.6.0"
}

=== rasa/scoops/ztree-zeta.json
{
    "version": "2.4.193",
    "description": "Text-mode file/directory manager (zeta version)",
    "homepage": "http://www.ztw3.com/forum/search.php?search=[zeta]",
    "license": "Shareware",
    "notes": "There is no way to uninstall just the zeta version",
    "depends": "ztree",
    "url": "http://www.ztree.com/download/ztw24193.zip",
    "hash": "4d0e29a3382e81ca1ef6e1d37dd89d252ac851f65679d328b196a539e216a6c0",
    "post_install": "cp \"$dir/*.*\" \"$(appdir ztree $global)/current\"",
    "checkver": {
        "re": "\\[Zeta\\] v([\\d.]+)\\s+"
    },
    "autoupdate": {
        "url": "http://www.ztree.com/download/ztw$cleanVersion.zip"
    }
}

=== rasa/scoops/bucket/lgpo.json
{
    "version": "2.2",
    "description": "Manage local group policy objects (LGPO)",
    "homepage": "https://www.microsoft.com/en-us/download/details.aspx?id=55319",
    "license": "Freeware",
    "url": "https://download.microsoft.com/download/8/5/C/85C25433-A1B0-4FFA-9429-7E023E7DA8D8/LGPO.zip",
    "hash": "6ffb6416366652993c992280e29faea3507b5b5aa661c33ba1af31f48acea9c4",
    "bin": "LGPO.exe"
}

=== rasa/scoops/listdosdevices.json
{
    "_comment": "checkver to be: ListDosDevices\\s+V([\\d.]+)",
    "bin": "ListDosDevices.exe",
    "description": "List DOS devices",
    "hash": "751055e9f84436afef2cf0547c04b65a136c8ebaabe0f1f3f973a63d21c263dd",
    "homepage": "http://www.uwe-sieber.de/drivetools_e.html",
    "license": "Freeware",
    "url": "http://www.uwe-sieber.de/files/listdosdevices.zip",
    "version": "0.2.1"
}

=== rasa/scoops/isobuster.json
{
    "autoupdate": {
        "url": "https://www.isobuster.com/dl.php?d=isobuster.com&v=1&l=0#/isobuster_install.exe"
    },
    "bin": "isobuster.exe",
    "checkver": {
        "re": "Download\\s+IsoBuster\\s+([\\d\\.]+)\\s*<",
        "url": "https://www.isobuster.com/download.php"
    },
    "description": "The ultimate data recovery software",
    "hash": "380ba4a7c9dcced8ad868f0334a1cf6d1bae8bbc93300143a98d830a317fe2a7",
    "homepage": "https://www.isobuster.com/",
    "innosetup": true,
    "license": "Shareware",
    "shortcuts": [
        [
            "isobuster.exe",
            "ISOBuster"
        ]
    ],
    "url": "https://www.isobuster.com/dl.php?d=isobuster.com&v=1&l=0#/isobuster_install.exe",
    "version": "4.3"
}

=== rasa/scoops/bucket/remount.json
{
    "version": "2.3",
    "description": "Remount ejected volumes",
    "homepage": "http://www.uwe-sieber.de/drivetools_e.html",
    "license": "Freeware",
    "architecture": {
        "32bit": {
            "bin": "Win32/remount.exe"
        },
        "64bit": {
            "bin": "x64/remount.exe"
        }
    },
    "url": "http://www.uwe-sieber.de/files/remount.zip",
    "hash": "9d258827401d2453a84e46acf76d074b9813f310cecb82c81f6a735a12d96a8e",
    "checkver": "ReMount\\s+V([\\d.]+)\\s+-",
    "autoupdate": {
        "url": "http://www.uwe-sieber.de/files/remount.zip"
    }
}

=== rasa/scoops/policy-analyzer.json
{
    "bin": [
        "PolicyRulesFileBuilder.exe",
        "PolicyAnalyzer_GetLocalPolicy.exe",
        "PolicyAnalyzer.exe"
    ],
    "hash": "66cec3c3b1fc3ce4291011d367577d725fe8839460483559e7383f0d124dbc94",
    "description": "LGPO policy analyzer",
    "license": "MSEULA",
    "url": "https://download.microsoft.com/download/8/5/C/85C25433-A1B0-4FFA-9429-7E023E7DA8D8/PolicyAnalyzer.zip",
    "version": "3.2.1705.29001",
    "homepage": "https://www.microsoft.com/en-us/download/details.aspx?id=55319"
}
